/**
 * Coloring Page Prompt Generator
 * Version 5.0
 *
 * Consumes Page Manifests
 * generated by the AI Planner.
 */

function buildColoringPagePrompt(
  pageManifest
) {

  const promptParts = [];

  //
  // Base Coloring Standards
  //

  promptParts.push(
    "Professional children's coloring book page."
  );

  promptParts.push(
    "Black and white line art."
  );

  promptParts.push(
    "Bold clean outlines."
  );

  promptParts.push(
    "Large coloring areas."
  );

  promptParts.push(
    "No shading."
  );

  promptParts.push(
    "No grayscale."
  );

  promptParts.push(
    "Printable Amazon KDP interior."
  );

  promptParts.push(
    "Ages 5-10."
  );

  //
  // Use AI Planned Content
  //

  if (
    pageManifest.title
  ) {

    promptParts.push(
      "Page Title:"
    );

    promptParts.push(
      pageManifest.title
    );

  }

  if (
    pageManifest.scripture
  ) {

    promptParts.push(
      "Scripture:"
    );

    promptParts.push(
      pageManifest.scripture
    );

  }

  if (
    pageManifest.visualDescription
  ) {

    promptParts.push(
      pageManifest.visualDescription
    );

  }

  //
  // Use Governed Prompt
  //

  if (
    pageManifest.imagePrompt
  ) {

    promptParts.push(
      pageManifest.imagePrompt
    );

  }

  return promptParts.join(
    " "
  );

}
